- hosts: all
  gather_facts: true
  tasks:     
  # Read a file
  - name: Display file content (/etc/redhat-release).........
    shell: cat /etc/redhat-release
    register: OSrelease_result
  - debug: msg="{{ OSrelease_result.stdout_lines }}"
